Models/Person.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AssurantAIZ.Models
{
	public class Person
	{
		[Required(AllowEmptyStrings = false, ErrorMessage = "Ingrese un nombre")]
		public string Name { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Ingrese la edad")]
        public int Age { get; set; }
		public bool IsMarried { get; set; }
	}
}

Models/UsuarioCondusefModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AssurantAIZ.Models
{
	public class UsuarioCondusefModel
	{
		[DisplayName("Clave")]
		[Required(AllowEmptyStrings = false, ErrorMessage = "Ingrese una clave")]
		public string Key { get; set; }
        [DisplayName("Usuario")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Ingrese un nombre de usuario")]
        public string UserName { get; set; }
        [DisplayName("Contraseña")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Ingrese una contraseña")]
        public string Password { get; set; }
	}
}

Controllers/AIZController.cs
using AssurantAIZ.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.ModelBinding;
using System.Web.Mvc;

namespace AssurantAIZ.Controllers
{
    public class AIZController : Controller
    {
        // GET: AIZ
        public ActionResult Index()
        {
            Person person = new Person { Name = "Jose", Age = 25, IsMarried = true };
            return View(person);
        }

        [HttpPost]
        public ActionResult Index(Person model)
        {
            if (this.HttpContext.Request.Files.Count > 0)
            {

                var uploadedFile = this.HttpContext.Request.Files.Get(0);

                if (uploadedFile.ContentLength > 0)
                {
                    if (ModelState.IsValid)
                    {
                        //ViewBag.ResponseJavaScriptFunction = "console.log('Modelo valido');";
                        string responseString = "Es usted una verga bien parada y \nQue chingue a su puta madre el America";
                        byte[] bytes = Encoding.UTF8.GetBytes(responseString);
                        return File(bytes, "text/plain", "textFile1.txt");

                    }
                }  
                else
                {
                    //ViewBag.ResponseJavaScriptFunction = "alert('Por favor seleccione un archivo');";
                }
            }
            
            return View(model);
        }
    }
}

Controllers/Example1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AssurantAIZ.Controllers
{
    public class Example1Controller : Controller
    {
        // GET: Example1
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Tabla1()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AssurantAIZ.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/UsuarioCondusefController.cs
using AssurantAIZ.Models;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.EnterpriseServices.Internal;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AssurantAIZ.Controllers
{
    public class UsuarioCondusefController : Controller
    {
        // GET: UsuarioCondusef
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(UsuarioCondusefModel model)
        {
            if (ModelState.IsValid)
            {
                ModelState.Clear();
                return View();
            }
            return View(model);
        }


        [HttpGet]
        [Route("Personas")]
        public ActionResult Personas(int draw, int start, int length)
        {
            string searchText = this.HttpContext.Request.QueryString["search[value]"];

            List<Person> personas = new List<Person>();
            Random random = new Random();

            for (int i = 0; i < 1000; i++)
            {
                personas.Add(new Person { Name = "Persona " + (i + 1).ToString(), Age = random.Next(15, 90), IsMarried = (i%2) == 0 ? true : false });
            }

            List<Person> filteredList = personas.Where(p => p.Name.Contains(searchText)).ToList();
            
            List<Person> paginatedResults = filteredList.Skip(start).Take(length).ToList();

            return Json(new { draw = draw, data = paginatedResults, recordsTotal = personas.Count, recordsFiltered = filteredList.Count }, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/AIZ/Index.cshtml
@model AssurantAIZ.Models.Person
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<nav class="navbar navbar-expand-lg g-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Condusef</a>
                </li>
            </ul> 
        </div> 
    </div>
</nav>
<div class="container-fluid">
    <form action="@Url.Action("Index")"  method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-12 col-md-4 col-lg-3">
                @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Name, null, new { style = "color: red;" })
            </div>
            <div class="col-12 col-md-4 col-lg-3">
                @Html.TextBoxFor(x => x.Age, new { @class = "form-control", type = "number" })
                @Html.ValidationMessageFor(x => x.Age, null, new { style = "color: red;" })
            </div>
            <div class="col-12 col-md-4 col-lg-3">
                @Html.CheckBoxFor(x => x.IsMarried, new { @class = "form-check" })
            </div>
            <div class="col-12 col-md-4 col-lg-3">
                <input type="file" name="excelFile" id="inpExcel" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" />
            </div>
        </div>
        <div class="row">
            <div class="col-12 offset-md-8 col-md-4 col-lg-2 col-offset-lg-10">
                <button class="btn btn-primary" type="submit">Aceptar</button>
            </div>
        </div>
    </form>
    <div class="row">
        <div class="col-12">
            <iframe id="mainIframe" style="width: 100%; height: 100%"></iframe>
        </div>
    </div>
</div>

<div class="modal" tabindex="-1" id="myModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Ejemplo</h5>
            </div>
            <div class="modal-body">
                <p style="color: red; font-size: 16px; font-weight:700">
                    Que chingue a su puta madre el America
                </p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" type="button" id="btnCloseModal">Aceptar</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function () {

        var myModal = new bootstrap.Modal(document.getElementById('myModal'), { keyboard: false, backdrop: true, focus: true });

        myModal.show();

        document.getElementById("btnCloseModal").addEventListener('click', function (ev) {
            if (myModal._isShown) {
                myModal.hide();
            }
        })

        @if (ViewBag.ResponseJavaScriptFunction != null)
        {
            @Html.Raw(ViewBag.ResponseJavaScriptFunction)
        }
    

        const links = document.getElementsByClassName('nav-link');
        for (let i = 0; i < links.length; i++) {
            const a = links.item(i);
            if (a.classList.contains('nav-link')) {
                a.addEventListener('click', function () {
                    const mainIframe = document.getElementById("mainIframe");
                    if (mainIframe instanceof HTMLIFrameElement) {
                        mainIframe.src = "";
                        mainIframe.src = '@Url.Action("Index", "Example1")'
                    }
                })
            }
        }
    })
</script>

Views/Example1/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div class="container-fluid w-100">
        <div class="row w-100">
            <form>
                <div class="col-12 col-md-4 col-lg-2">
                    <select class="form-select" style="width:100%;">
                        <option value="1">opcion 1</option>
                        <option value="2">opcion 2</option>
                        <option value="3">opcion 3</option>
                    </select>
                </div>
            </form>
        </div>
        <div class="row w-100">
            <div class="col-12">
                @Html.Partial("Tabla1")
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>

Views/Example1/Tabla1.cshtml
<table class="table table-striped table-responsive">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Edad</th>
            <th>Estado Civil</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Luis</td>
            <td>36</td>
            <td>Soltero</td>
        </tr>
        <tr>
            <td>Maria</td>
            <td>25</td>
            <td>Casada</td>
        </tr>
        <tr>
            <td>Alberto</td>
            <td>32</td>
            <td>Soltero</td>
        </tr>
    </tbody>
</table>

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Assurant", "Index", "AIZ", new { area = "" }, new { @class = "nav-link" }) </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/UsuarioCondusef/Index.cshtml
@model AssurantAIZ.Models.UsuarioCondusefModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>

        .LabelInput {
            font-weight: 600;
            color: #000000;
        }

        .MessageError {
            color: red;
        }
    </style>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <link rel="stylesheet" href="~/Scripts/libs/jquery-ui-1.14.1/jquery-ui.theme.css" />
    <link rel="stylesheet" href="~/Scripts/libs/jquery-ui-1.14.1/jquery-ui.css" />
    <link rel="stylesheet" href="~/Scripts/libs/jquery-ui-1.14.1/jquery-ui.structure.css" />
    <script type="text/javascript" src="~/Scripts/libs/jquery-ui-1.14.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="~/Scripts/datatables.css" />
    <script type="text/javascript" src="~/Scripts/datatables.js"></script>
</head>
<body>
    @*<div class="container">
        <form method="post">
            <div class="row">
                <div class="col-12 col-md-4 col-lg-3">
                    @Html.LabelFor(x => x.Key, new { @class = "LabelInput" })
                    @Html.TextBoxFor(x => x.Key, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Key, null, new { @class = "MessageError" })
                </div>
                <div class="col-12 col-md-4 col-lg-3">
                    @Html.LabelFor(x => x.UserName, new { @class = "LabelInput" })
                    @Html.TextBoxFor(x => x.UserName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.UserName, null, new { @class = "MessageError" })
                </div>
                <div class="col-12 col-md-4 col-lg-3">
                    @Html.LabelFor(x => x.Password, new { @class = "LabelInput" })
                    @Html.PasswordFor(x => x.Password, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Password, null, new { @class = "MessageError" })
                </div>
            </div>
            <div class="row">
                <div class="col-12 col-md-3 offset-md-9 col-lg-2 offset-lg-10">
                    <button type="submit" class="btn btn-primary w-100">Crear Usuario</button>
                </div>
            </div>
        </form>
    </div>*@
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-3">
                <input type="text" class="form-control datepicker-Form" id="inpDateStart"/>
            </div>
            <div class="col-12 col-md-3">
                <input type="text" class="form-control datepicker-Form" id="inpDateEnd"/>
            </div>
            <div class="col-12 col-md-3">
                <input type="text" class="form-control" id="inpUser"/>
            </div>
            <div class="col-12 col-md-3">
                <button type="button" class="btn btn-primary" id="btnSearch">Buscar</button>
            </div>
        </div>
    </div>
    <div class="container">
        <table id="userTable" class="table-responsive table table-striped">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Edad</th>
                    <th>Casado</th>
                </tr>
            </thead>
        </table>
    </div>
    
    <script type="text/javascript">

        document.addEventListener("DOMContentLoaded", function () {

            $(".form-control.datepicker-Form").datepicker({
                changeMonth: true,
                changeYear: true,
                dateFormat: "dd/mm/yy"
            })

            let userTable = new DataTable(document.getElementById("userTable"), {
                searching: false,
                processing: true,
                serverSide: true,
                ajax: {
                    url: "@Url.Action("Personas")",
                    method: "GET",
                    dataSrc: "data"
                },

                columns: [
                    {
                        data: 'Name'
                    },
                    {
                        data: 'Age'
                    },
                    {
                        data: 'IsMarried',
                        render: function (data, type) {
                            if (typeof data === 'boolean') {
                                if (data) {
                                    return '<input type="checkbox" checked /> '
                                }
                                return '<input type="checkbox" /> '
                            }
                        }
                    }
                ],
                language:{
                    "decimal": "",
                    "emptyTable": "Informacion no disponible en la tabla",
                    "info": "Mostrando _START_ a _END_ de _TOTAL_ registros",
                    "infoEmpty": "Mostrando 0 a 0 de 0 registros",
                    "infoFiltered": "(Filtrado de _MAX_ total registros)",
                    "infoPostFix": "",
                    "thousands": ",",
                    "lengthMenu": "Mostrar _MENU_ registros",
                    "loadingRecords": "Cargar...",
                    "processing": "",
                    "search": "Buscar:",
                    "zeroRecords": "No se encontraron registros",
                    "paginate": {
                        "first": "Primero",
                        "last": "Ultimo",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    },
                    "aria": {
                        "orderable": "Ordenar por esta columna",
                        "orderableReverse": "Ordenar en reversa esta columna"
                    }
                }
            })

            document.getElementById("btnSearch").addEventListener("click", function (evt) {
                if (typeof userTable === 'object') {
                    userTable.ajax.reload();
                }
            })
        })
    </script>
</body>
</html>